import { Box } from '@mui/material';
import './PoliticaDePrivacidade.css';

const PoliticaDePrivacidade = () => {
    return (
        <Box className='container' sx={{margin: '200px auto 180px auto', width: '1200px'}}>
        <h1 className='title-desktop'>Politica de Privacidade</h1>
        <h3 className='subtitle-desktop'>Segurança e Confidencialidade</h3>
        <p className='text-desktop'>A sua privacidade é muito importante para nós, por isso tratamos todas as informações de usuários e clientes com a máxima confidencialidade. É política do Monbank respeitar a sua privacidade em relação a qualquer informação e/ou dados coletados no site https://www.monbank.net e demais meios digitais da empresa.</p>
        <p className='text-desktop'>Solicitamos informações pessoais tais como nome, endereço, e-mail e telefone com o objetivo de facilitar a comunicação entre nossa empresa e você, visando a prestação de um serviço adequado, realizado por meios justos e legais, com o seu conhecimento e consentimento, através do cadastramento em formulários, sendo que a coleta se dá de forma individual. Ao realizar o preenchimento dos dados no formulário apresentado, fica explícito que o usuário aceita os termos e condições da política de privacidade do Monbank.</p>
        <p className='text-desktop'>Assim sendo, o conteúdo aqui apresentado visa o esclarecimento quanto ao serviço disponibilizado em meios de contato em nosso site e páginas das redes sociais.</p>
        <p className='text-desktop'>O Monbank retém as informações coletadas pelo tempo necessário para fornecer o serviço solicitado.</p>
        <p className='text-desktop'>Quando armazenamos dados, protegemos sua integridade dentro de meios comercialmente aceitáveis para evitar perdas e roubos, bem como acesso, divulgação, cópia, uso ou modificação não autorizados.</p>
        <p className='text-desktop'>Os dados dos usuários e clientes que forem coletados em nossos meios digitais serão acessados restritamente por funcionários autorizados pelo Monbank, bem como por empresas parceiras, especificamente para o uso apropriado das informações no âmbito da comercialização dos produtos do Monbank, a fim de aprimorar a experiência de compra do imóvel e atualizar sobre os lançamentos de empreendimentos da nossa empresa. Se houver quaisquer irregularidades na utilização dos dados coletados, em desacordo com a presente política de privacidade, manual de conduta do Monbank e/ou normas e dispositivos legais, ficarão sujeitos às medidas disciplinares e legais cabíveis à espécie.</p>
        <p className='text-desktop'>Somente compartilhamos dados e informações pessoais com empresas parceiras, as quais igualmente devem observar as normas da Lei Geral de Proteção de Dados e com o único objetivo de fornecer aos interessados, em nome do Monbank, maiores informações sobre nossos empreendimentos, de modo a cumprir o propósito para o qual os dados foram coletados, ou, ainda, em circunstâncias especificas determinadas e advindas por lei.</p>
        <p className='text-desktop'>Em hipótese alguma seus dados serão vendidos ou transferidos para empresas que não sejam as parceiras credenciadas com o Monbank.</p>
        <p className='text-desktop'>O nosso site pode conter links para sites externos que não são operados pelo Monbank, de modo que não nos responsabilizamos sobre o conteúdo e práticas desses sites nos quais possuem suas próprias respectivas políticas de privacidade.</p>
        <p className='text-desktop'>O uso continuado de nosso site será considerado como aceitação de nossas práticas em torno de privacidade e informações pessoais. Se você tiver alguma dúvida sobre como lidamos com dados do usuário e informações pessoais, entre em contato conosco.</p>
        <p className='text-desktop'>Os dados pessoais fornecidos são mantidos em absoluto sigilo e serão utilizados para fins específicos como resposta a e-mails, inscrição e para que o Monbank possa enviar informações ou ofertas a respeito de seus empreendimentos.</p>
        <p className='text-desktop'>Além disso, a única forma de utilização diversa dos dados e transferência de informações e/ou dados pessoais poderá ocorrer por força de determinação judicial ou legal.</p>
        <p className='text-desktop'>Os seus dados para contato são utilizados no intuito de divulgar mais informações sobre nossos empreendimentos, e, quando solicitado por você, para comunicar novidades e serviços da empresa, podendo, a qualquer momento, solicitar a exclusão de seus dados do nosso cadastro.</p>
        <p className='text-desktop'>O usuário concorda com os termos e condições da política de privacidade, de forma irrestrita, quando faz o cadastro, acessa ou utiliza os serviços de contato do Monbank.</p>
        <p className='text-desktop'>O Monbank tem o compromisso de aprimorar os serviços e funções disponíveis em sua página, com a observância dos dados e informações colhidas em conjunto com usuários do site, visando a melhoria das funcionabilidades e aplicabilidades do website.</p>
        <h3 className='subtitle-desktop'>Direitos de autor e propriedade intelectual</h3>
        <p className='text-desktop'>Todo o conteúdo das páginas deste website, salvo disposição em contrário, tais como logotipo, informações, materiais, instrumentos, organização da página, gráficos e desenhos, são de propriedade do Monbank ou de terceiros que autorizaram e ou cederam seu direito de uso. Não é permitido o uso, cópia ou reprodução, integral ou parcial, dos textos e/ou imagens, sem autorização específica. Salientamos que a utilização não autorizada, infringe as leis de marcas e patentes, de direitos autorais, da propriedade intelectual e da privacidade e publicidade.</p>    
        <h3 className='subtitle-desktop'>Política de Cookies</h3>
        <p className='text-desktop'>Como é prática comum em quase todos os sites profissionais, este site utiliza cookies, que são arquivos ou informações que podem ser armazenadas em seus dispositivos quando você visita os websites ou utiliza os serviços on-line. Geralmente, um cookie contém o nome do site que o originou, seu tempo de vida e um valor, que é gerado aleatoriamente.</p>
        <p className='text-desktop'>Infelizmente, na maioria dos casos, não existem opções padrão do setor para desativar os cookies sem desativar completamente a funcionalidade e os recursos que eles adicionam a este site. É recomendável que você deixe todos os cookies se não tiver certeza se precisa ou não deles, caso sejam usados para fornecer um serviço que você usa.</p>
        <p className='text-desktop'>Você pode impedir a configuração de cookies ajustando as configurações do seu navegador, porém a desativação de cookies afetará a funcionalidade deste e de muitos outros sites que você visita. A desativação de cookies geralmente resultará na desativação de determinadas funcionalidades e recursos deste site. Portanto, é recomendável que você não desative os cookies.</p>
        <p className='text-desktop'>O Monbank utiliza cookies para facilitar o uso e melhor adaptar seu website e aplicações aos interesses e necessidades de seus Usuários, bem como para auxiliar e melhorar suas estruturas e seus conteúdos. Os cookies também podem ser utilizados para acelerar suas atividades e experiências futuras em nossos serviços.</p>
        <p className='text-desktop'>Por meio de cookies, o site armazena informações sobre as atividades do navegador, incluindo endereço IP e a página acessada. Esses registros de atividades (logs) serão utilizados apenas para fins estatísticos e de métricas dos serviços disponibilizados ou para a investigação de fraudes ou de alterações indevidas em seus sistemas e cadastros, não tendo como finalidade o fornecimento dos dados a terceiros sem autorização expressa do Usuário.</p>
        <p className='text-desktop'>Esses registros poderão compreender dados como o endereço IP do Usuário, as ações efetuadas no site, as páginas acessadas, as datas e horários de cada ação e de acesso a cada página do site, as informações sobre o dispositivo utilizado, versão de sistema operacional, navegador, dentre outros aplicativos instalados.</p>
        <p className='text-desktop'>Este site usa o Google Analytics, que é uma das soluções de análise mais difundidas e confiáveis da Web, para nos ajudar a entender como você usa o site e como podemos melhorar sua experiência. Esses cookies podem rastrear itens como quanto tempo você gasta no site e as páginas visitadas, para que possamos continuar produzindo conteúdo atraente.</p>
        <p className='text-desktop'>As análises de terceiros são usadas para rastrear e medir o uso deste site, para que possamos continuar produzindo conteúdo atrativo. Esses cookies podem rastrear itens como o tempo que você passa no site ou as páginas visitadas, o que nos ajuda a entender como podemos melhorar o site para você.</p>
        <p className='text-desktop'>À medida que vendemos produtos, é importante entendermos as estatísticas sobre quantos visitantes de nosso site realmente compram e, portanto, esse é o tipo de dados que esses cookies rastrearão. Isso é importante para você, pois significa que podemos fazer previsões de negócios com precisão que nos permitem analisar nossos custos de publicidade e produtos para garantir o melhor preço possível.</p>
        <h3 className='subtitle-desktop'>Formas de contato</h3>
        <p className='text-desktop'>Ao entrar em contato com o Monbank, usuário permite que a empresa possa contatá-lo via e-mail, ligação, sms, cartas ou whatsapp. Essa permissão é necessária para que a empresa possa atender a fornecedores, clientes e parceiros da melhor forma.</p>
        <h3 className='subtitle-desktop'>Mais infromações</h3>
        <p className='text-desktop'>Esta política de privacidade poderá ser alterada periodicamente e a atualização será publicada nos meios digitais da empresa.</p>

        </Box>
    );
    }

export default PoliticaDePrivacidade;